{"info": {"author": "Christopher H. Todd", "author_email": "Christopher.Hayden.Todd@gmail.com", "bugtrack_url": null, "classifiers": ["Development Status :: 5 - Production/Stable", "Intended Audience :: Developers", "Natural Language :: English", "Programming Language :: Python", "Programming Language :: Python :: 3", "Programming Language :: Python :: 3.6", "Programming Language :: Python :: 3.7", "Programming Language :: Python :: 3.8"], "description": "# Christopher H. Todd's PROJECT_STRING_NAME\n\nThe PROJECT_GIT_NAME project is responsible for ...\n\nThe library ...\n\n## Table of Contents\n\n- [Dependencies](#dependencies)\n- [Libraries](#libraries)\n- [Example Scripts](#example-scripts)\n- [Notes](#notes)\n- [TODO](#todo)\n\n## Dependencies\n\n### Python Packages\n\n- N/A\n\n## Libraries\n\n### [create_exceptions.py](https://github.com/ChristopherHaydenTodd/ctodd-python-lib-exceptions/blob/master/exceptions_helpers/create_exceptions.py]create_exceptions.py)\n\nException Helpers. This file shows exception types in Python and function calls for generating specific exceptions. This can be useful for unittesting, debugging, and other tasks that might call for purposefully breaking parts of your code.\n\nFunctions:\n\n```\ndef create_and_throw_exception(exception_name=None):\n    \"\"\"\n        Purpose:\n            Create and Throw an exception from the exception\n            types in the file. if exception_name is passed in,\n            throw that specific exception if it has been\n            coded in the library\n        Args:\n            exception_name (String ExceptionType): Type of exception\n                to throw\n        Returns:\n            N/A: should never return, should always raise\n    \"\"\"\n```\n\n```\ndef create_zero_division_exception():\n    \"\"\"\n        Purpose:\n            Throw ZeroDivisionError Exception\n        Args:\n            N/A\n        Returns:\n            N/A\n    \"\"\"\n```\n\n```\ndef create_overflow_exception():\n    \"\"\"\n        Purpose:\n            Throw OverflowError Exception\n        Args:\n            N/A\n        Returns:\n            N/A\n    \"\"\"\n```\n\n```\ndef create_type_exception():\n    \"\"\"\n        Purpose:\n            Throw TypeError Exception\n        Args:\n            N/A\n        Returns:\n            N/A\n    \"\"\"\n```\n\n```\ndef create_assertion_exception():\n    \"\"\"\n        Purpose:\n            Throw AssertionError Exception\n        Args:\n            N/A\n        Returns:\n            N/A\n    \"\"\"\n```\n\n```\ndef create_attribute_exception():\n    \"\"\"\n        Purpose:\n            Throw AttributeError Exception\n        Args:\n            N/A\n        Returns:\n            N/A\n    \"\"\"\n```\n\n```\ndef create_name_exception():\n    \"\"\"\n        Purpose:\n            Throw NameError Exception\n        Args:\n            N/A\n        Returns:\n            N/A\n    \"\"\"\n```\n\n```\ndef create_index_exception():\n    \"\"\"\n        Purpose:\n            Throw IndexError Exception\n        Args:\n            N/A\n        Returns:\n            N/A\n    \"\"\"\n```\n\n```\ndef create_key_exception():\n    \"\"\"\n        Purpose:\n            Throw KeyError Exception\n        Args:\n            N/A\n        Returns:\n            N/A\n    \"\"\"\n```\n\n```\ndef create_unbound_local_exception():\n    \"\"\"\n        Purpose:\n            Throw UnboundLocalError Exception\n        Args:\n            N/A\n        Returns:\n            N/A\n    \"\"\"\n```\n\n### [unsupported_exception.py](https://github.com/ChristopherHaydenTodd/ctodd-python-lib-exceptions/blob/master/exceptions_helpers/create_exceptions.py]unsupported_exception.py)\n\nUnsupportedException Class. Currently Does Nothing, but allows for sepcific callouts of failures in create_exceptions\n\nClasses:\n\n```\nclass UnsupportedException(Exception):\n    \"\"\"\n    Purpose:\n        An Unsupported Exception is raised when the lib is asked to try\n        and raise an exception that has yet to be programmed. this way,\n        som exception is raised, but it can be handled in a way that\n        knows the specified exception isn't raised\n    \"\"\"\n```\n\n## Example Scripts\n\nExample executable Python scripts/modules for testing and interacting with the library. These show example use-cases for the libraries and can be used as templates for developing with the libraries or to use as one-off development efforts.\n\n### N/A\n\n## Notes\n\n - Relies on f-string notation, which is limited to Python3.6.  A refactor to remove these could allow for development with Python3.0.x through 3.5.x\n\n## TODO\n\n - Unittest framework in place, but lacking tests\n\n\n", "description_content_type": "text/markdown", "docs_url": null, "download_url": "", "downloads": {"last_day": -1, "last_month": -1, "last_week": -1}, "home_page": "https://github.com/ChristopherHaydenTodd/ctodd-python-lib-exceptions", "keywords": "python,libraries,exceptions", "license": "MIT", "maintainer": "", "maintainer_email": "", "name": "ctodd-python-lib-exceptions", "package_url": "https://pypi.org/project/ctodd-python-lib-exceptions/", "platform": "", "project_url": "https://pypi.org/project/ctodd-python-lib-exceptions/", "project_urls": {"Homepage": "https://github.com/ChristopherHaydenTodd/ctodd-python-lib-exceptions"}, "release_url": "https://pypi.org/project/ctodd-python-lib-exceptions/1.0.0/", "requires_dist": null, "requires_python": ">3.6", "summary": "Python utilities used for handling and raising exceptions", "version": "1.0.0", "yanked": false, "html_description": "<div class=\"project-description\">\n            <h1>Christopher H. Todd's PROJECT_STRING_NAME</h1>\n<p>The PROJECT_GIT_NAME project is responsible for ...</p>\n<p>The library ...</p>\n<h2>Table of Contents</h2>\n<ul>\n<li><a href=\"#dependencies\" rel=\"nofollow\">Dependencies</a></li>\n<li><a href=\"#libraries\" rel=\"nofollow\">Libraries</a></li>\n<li><a href=\"#example-scripts\" rel=\"nofollow\">Example Scripts</a></li>\n<li><a href=\"#notes\" rel=\"nofollow\">Notes</a></li>\n<li><a href=\"#todo\" rel=\"nofollow\">TODO</a></li>\n</ul>\n<h2>Dependencies</h2>\n<h3>Python Packages</h3>\n<ul>\n<li>N/A</li>\n</ul>\n<h2>Libraries</h2>\n<h3><a href=\"https://github.com/ChristopherHaydenTodd/ctodd-python-lib-exceptions/blob/master/exceptions_helpers/create_exceptions.py%5Dcreate_exceptions.py\" rel=\"nofollow\">create_exceptions.py</a></h3>\n<p>Exception Helpers. This file shows exception types in Python and function calls for generating specific exceptions. This can be useful for unittesting, debugging, and other tasks that might call for purposefully breaking parts of your code.</p>\n<p>Functions:</p>\n<pre><code>def create_and_throw_exception(exception_name=None):\n    \"\"\"\n        Purpose:\n            Create and Throw an exception from the exception\n            types in the file. if exception_name is passed in,\n            throw that specific exception if it has been\n            coded in the library\n        Args:\n            exception_name (String ExceptionType): Type of exception\n                to throw\n        Returns:\n            N/A: should never return, should always raise\n    \"\"\"\n</code></pre>\n<pre><code>def create_zero_division_exception():\n    \"\"\"\n        Purpose:\n            Throw ZeroDivisionError Exception\n        Args:\n            N/A\n        Returns:\n            N/A\n    \"\"\"\n</code></pre>\n<pre><code>def create_overflow_exception():\n    \"\"\"\n        Purpose:\n            Throw OverflowError Exception\n        Args:\n            N/A\n        Returns:\n            N/A\n    \"\"\"\n</code></pre>\n<pre><code>def create_type_exception():\n    \"\"\"\n        Purpose:\n            Throw TypeError Exception\n        Args:\n            N/A\n        Returns:\n            N/A\n    \"\"\"\n</code></pre>\n<pre><code>def create_assertion_exception():\n    \"\"\"\n        Purpose:\n            Throw AssertionError Exception\n        Args:\n            N/A\n        Returns:\n            N/A\n    \"\"\"\n</code></pre>\n<pre><code>def create_attribute_exception():\n    \"\"\"\n        Purpose:\n            Throw AttributeError Exception\n        Args:\n            N/A\n        Returns:\n            N/A\n    \"\"\"\n</code></pre>\n<pre><code>def create_name_exception():\n    \"\"\"\n        Purpose:\n            Throw NameError Exception\n        Args:\n            N/A\n        Returns:\n            N/A\n    \"\"\"\n</code></pre>\n<pre><code>def create_index_exception():\n    \"\"\"\n        Purpose:\n            Throw IndexError Exception\n        Args:\n            N/A\n        Returns:\n            N/A\n    \"\"\"\n</code></pre>\n<pre><code>def create_key_exception():\n    \"\"\"\n        Purpose:\n            Throw KeyError Exception\n        Args:\n            N/A\n        Returns:\n            N/A\n    \"\"\"\n</code></pre>\n<pre><code>def create_unbound_local_exception():\n    \"\"\"\n        Purpose:\n            Throw UnboundLocalError Exception\n        Args:\n            N/A\n        Returns:\n            N/A\n    \"\"\"\n</code></pre>\n<h3><a href=\"https://github.com/ChristopherHaydenTodd/ctodd-python-lib-exceptions/blob/master/exceptions_helpers/create_exceptions.py%5Dunsupported_exception.py\" rel=\"nofollow\">unsupported_exception.py</a></h3>\n<p>UnsupportedException Class. Currently Does Nothing, but allows for sepcific callouts of failures in create_exceptions</p>\n<p>Classes:</p>\n<pre><code>class UnsupportedException(Exception):\n    \"\"\"\n    Purpose:\n        An Unsupported Exception is raised when the lib is asked to try\n        and raise an exception that has yet to be programmed. this way,\n        som exception is raised, but it can be handled in a way that\n        knows the specified exception isn't raised\n    \"\"\"\n</code></pre>\n<h2>Example Scripts</h2>\n<p>Example executable Python scripts/modules for testing and interacting with the library. These show example use-cases for the libraries and can be used as templates for developing with the libraries or to use as one-off development efforts.</p>\n<h3>N/A</h3>\n<h2>Notes</h2>\n<ul>\n<li>Relies on f-string notation, which is limited to Python3.6.  A refactor to remove these could allow for development with Python3.0.x through 3.5.x</li>\n</ul>\n<h2>TODO</h2>\n<ul>\n<li>Unittest framework in place, but lacking tests</li>\n</ul>\n\n          </div>"}, "last_serial": 5170019, "releases": {"1.0.0": [{"comment_text": "", "digests": {"md5": "eab3efe3bf725c5ed9ab4a334b9114ed", "sha256": "08e3f331b62a577acb3566cdaa4574fa25c9a0a1c826070c6ef55affea94f454"}, "downloads": -1, "filename": "ctodd_python_lib_exceptions-1.0.0-py3-none-any.whl", "has_sig": false, "md5_digest": "eab3efe3bf725c5ed9ab4a334b9114ed", "packagetype": "bdist_wheel", "python_version": "py3", "requires_python": ">3.6", "size": 6917, "upload_time": "2019-04-21T15:01:09", "upload_time_iso_8601": "2019-04-21T15:01:09.734322Z", "url": "https://files.pythonhosted.org/packages/57/51/38adf14e77e52afc727c3e4d0c978131384c60097b198847abb352f831d1/ctodd_python_lib_exceptions-1.0.0-py3-none-any.whl", "yanked": false}, {"comment_text": "", "digests": {"md5": "34ce6c025aeb6b380d08fd2beed8b054", "sha256": "0fdf500f3499ed1d49740591f8e1337e0506f81356f5750c3d87c1def74cf853"}, "downloads": -1, "filename": "ctodd-python-lib-exceptions-1.0.0.tar.gz", "has_sig": false, "md5_digest": "34ce6c025aeb6b380d08fd2beed8b054", "packagetype": "sdist", "python_version": "source", "requires_python": ">3.6", "size": 6214, "upload_time": "2019-04-21T15:01:11", "upload_time_iso_8601": "2019-04-21T15:01:11.792819Z", "url": "https://files.pythonhosted.org/packages/9e/ca/53ba7de1763ac0527cef926cd7fec3982037448552ac82e6346e80b92f09/ctodd-python-lib-exceptions-1.0.0.tar.gz", "yanked": false}]}, "urls": [{"comment_text": "", "digests": {"md5": "eab3efe3bf725c5ed9ab4a334b9114ed", "sha256": "08e3f331b62a577acb3566cdaa4574fa25c9a0a1c826070c6ef55affea94f454"}, "downloads": -1, "filename": "ctodd_python_lib_exceptions-1.0.0-py3-none-any.whl", "has_sig": false, "md5_digest": "eab3efe3bf725c5ed9ab4a334b9114ed", "packagetype": "bdist_wheel", "python_version": "py3", "requires_python": ">3.6", "size": 6917, "upload_time": "2019-04-21T15:01:09", "upload_time_iso_8601": "2019-04-21T15:01:09.734322Z", "url": "https://files.pythonhosted.org/packages/57/51/38adf14e77e52afc727c3e4d0c978131384c60097b198847abb352f831d1/ctodd_python_lib_exceptions-1.0.0-py3-none-any.whl", "yanked": false}, {"comment_text": "", "digests": {"md5": "34ce6c025aeb6b380d08fd2beed8b054", "sha256": "0fdf500f3499ed1d49740591f8e1337e0506f81356f5750c3d87c1def74cf853"}, "downloads": -1, "filename": "ctodd-python-lib-exceptions-1.0.0.tar.gz", "has_sig": false, "md5_digest": "34ce6c025aeb6b380d08fd2beed8b054", "packagetype": "sdist", "python_version": "source", "requires_python": ">3.6", "size": 6214, "upload_time": "2019-04-21T15:01:11", "upload_time_iso_8601": "2019-04-21T15:01:11.792819Z", "url": "https://files.pythonhosted.org/packages/9e/ca/53ba7de1763ac0527cef926cd7fec3982037448552ac82e6346e80b92f09/ctodd-python-lib-exceptions-1.0.0.tar.gz", "yanked": false}], "timestamp": "Fri May  8 00:41:36 2020"}