{"info": {"author": "Quantitative Engineering Design Inc.", "author_email": "info@qed.ai", "bugtrack_url": null, "classifiers": ["Environment :: Web Environment", "Framework :: Django", "Intended Audience :: Developers", "License :: OSI Approved :: BSD License", "Operating System :: OS Independent", "Programming Language :: Python :: 2.7", "Programming Language :: Python :: 3", "Programming Language :: Python :: 3.4", "Programming Language :: Python :: 3.5", "Programming Language :: Python :: 3.6"], "description": "UNKNOWN", "description_content_type": null, "docs_url": null, "download_url": "UNKNOWN", "downloads": {"last_day": -1, "last_month": -1, "last_week": -1}, "home_page": "https://qed.ai/", "keywords": null, "license": "UNKNOWN", "maintainer": null, "maintainer_email": null, "name": "django-force-error", "package_url": "https://pypi.org/project/django-force-error/", "platform": "UNKNOWN", "project_url": "https://pypi.org/project/django-force-error/", "project_urls": {"Download": "UNKNOWN", "Homepage": "https://qed.ai/"}, "release_url": "https://pypi.org/project/django-force-error/1.0.0b1/", "requires_dist": null, "requires_python": null, "summary": "Ready to use Django views that produce errors for testing your error reporting.", "version": "1.0.0b1", "yanked": false, "html_description": "<div class=\"project-description\">\n            <p>UNKNOWN</p>\n\n          </div>"}, "last_serial": 2720136, "releases": {"1.0.0b0": [{"comment_text": "", "digests": {"md5": "d8b44904eb30cf416633f9de879dbeb5", "sha256": "5afab52553b56fba57d6db418b6eebde504f59176444d4b7585a887408b0be40"}, "downloads": -1, "filename": "django-force-error-1.0.0b0.tar.gz", "has_sig": false, "md5_digest": "d8b44904eb30cf416633f9de879dbeb5", "packagetype": "sdist", "python_version": "source", "requires_python": null, "size": 1249, "upload_time": "2017-03-21T10:24:29", "upload_time_iso_8601": "2017-03-21T10:24:29.497620Z", "url": "https://files.pythonhosted.org/packages/8e/6a/b5687250f6f177e2a04ce7f72776763ede5ae0f85a690a13e1112080be42/django-force-error-1.0.0b0.tar.gz", "yanked": false}], "1.0.0b1": [{"comment_text": "", "digests": {"md5": "0bcdb880d937b3ea951f46b52026a342", "sha256": "256ba1a00c074e6e9b655815b712c97dce5ed2f631dc22621a8f21c65327e9bc"}, "downloads": -1, "filename": "django-force-error-1.0.0b1.tar.gz", "has_sig": false, "md5_digest": "0bcdb880d937b3ea951f46b52026a342", "packagetype": "sdist", "python_version": "source", "requires_python": null, "size": 1244, "upload_time": "2017-03-21T10:44:28", "upload_time_iso_8601": "2017-03-21T10:44:28.871353Z", "url": "https://files.pythonhosted.org/packages/d6/51/bcea216895a01a3511508cd5b58bc4c8d5fa77756d4a46610cc4a1c13491/django-force-error-1.0.0b1.tar.gz", "yanked": false}]}, "urls": [{"comment_text": "", "digests": {"md5": "0bcdb880d937b3ea951f46b52026a342", "sha256": "256ba1a00c074e6e9b655815b712c97dce5ed2f631dc22621a8f21c65327e9bc"}, "downloads": -1, "filename": "django-force-error-1.0.0b1.tar.gz", "has_sig": false, "md5_digest": "0bcdb880d937b3ea951f46b52026a342", "packagetype": "sdist", "python_version": "source", "requires_python": null, "size": 1244, "upload_time": "2017-03-21T10:44:28", "upload_time_iso_8601": "2017-03-21T10:44:28.871353Z", "url": "https://files.pythonhosted.org/packages/d6/51/bcea216895a01a3511508cd5b58bc4c8d5fa77756d4a46610cc4a1c13491/django-force-error-1.0.0b1.tar.gz", "yanked": false}], "timestamp": "Fri May  8 00:36:02 2020"}