{"info": {"author": "Sreejith Unnikrishnan", "author_email": "UNKNOWN", "bugtrack_url": null, "classifiers": ["Development Status :: 4 - Beta", "Intended Audience :: Developers", "License :: OSI Approved :: MIT License", "Programming Language :: Python :: 2", "Programming Language :: Python :: 2.6", "Programming Language :: Python :: 2.7", "Topic :: Utilities"], "description": "PyExceptionInfo: Easily lookup your errors on the web\r\n=====================================================\r\n\r\n# Exceptions happen\r\n\r\nExceptions do happen and we all have seen it more than once while we are\r\ndeveloping our code. Mostly we would want to know more about the exception or\r\nerror that we generated and the logical step that follows up is to inspect our\r\ncode and still if we are stuck, we might lookup on the internet.\r\n\r\nPyExceptionInfo helps you on the last part. Use it in your exception handling,\r\nand it will automatically lookup the exception on Google for you.\r\n\r\n## Installation\r\n\r\nUse pip for Installation\r\n\r\n    pip install PyExceptionInfo\r\n\r\n## Example\r\n\r\nLook up the test.py source code for usage\r\n\r\n    import PyExceptionInfo\r\n\r\n    try:\r\n        # Some exception here\r\n    except Exception as e:\r\n        PyExceptionInfo.getInfo(e)\r\n\r\nThanks!", "description_content_type": null, "docs_url": null, "download_url": "UNKNOWN", "downloads": {"last_day": -1, "last_month": -1, "last_week": -1}, "home_page": "https://github.com/srunnikr/PyExceptionInfo", "keywords": "error handling exception development", "license": "MIT", "maintainer": null, "maintainer_email": null, "name": "PyExceptionInfo", "package_url": "https://pypi.org/project/PyExceptionInfo/", "platform": "UNKNOWN", "project_url": "https://pypi.org/project/PyExceptionInfo/", "project_urls": {"Download": "UNKNOWN", "Homepage": "https://github.com/srunnikr/PyExceptionInfo"}, "release_url": "https://pypi.org/project/PyExceptionInfo/0.2/", "requires_dist": null, "requires_python": null, "summary": "PyExceptionInfo: Easily lookup the exception on web", "version": "0.2", "yanked": false, "html_description": "<div class=\"project-description\">\n            <p># Exceptions happen</p>\n<p>Exceptions do happen and we all have seen it more than once while we are\ndeveloping our code. Mostly we would want to know more about the exception or\nerror that we generated and the logical step that follows up is to inspect our\ncode and still if we are stuck, we might lookup on the internet.</p>\n<p>PyExceptionInfo helps you on the last part. Use it in your exception handling,\nand it will automatically lookup the exception on Google for you.</p>\n<p>## Installation</p>\n<p>Use pip for Installation</p>\n<blockquote>\npip install PyExceptionInfo</blockquote>\n<p>## Example</p>\n<p>Look up the test.py source code for usage</p>\n<blockquote>\n<p>import PyExceptionInfo</p>\n<dl>\n<dt>try:</dt>\n<dd># Some exception here</dd>\n<dt>except Exception as e:</dt>\n<dd>PyExceptionInfo.getInfo(e)</dd>\n</dl>\n</blockquote>\n<p>Thanks!</p>\n\n          </div>"}, "last_serial": 2202252, "releases": {"0.1": [{"comment_text": "", "digests": {"md5": "8c9eaabcbdefc925d1734f17e9671073", "sha256": "eb4f949feac55ff5b29e71dfba357406c30349c4b4cea2df287a8ae9d3ba31c1"}, "downloads": -1, "filename": "PyExceptionInfo-0.1-py2-none-any.whl", "has_sig": false, "md5_digest": "8c9eaabcbdefc925d1734f17e9671073", "packagetype": "bdist_wheel", "python_version": "py2", "requires_python": null, "size": 2832, "upload_time": "2016-07-04T18:50:03", "upload_time_iso_8601": "2016-07-04T18:50:03.311828Z", "url": "https://files.pythonhosted.org/packages/d3/56/bc1adde9b52fb236d1b5c7aa37c1fa7d0970bc38cb629ff00fc5a1b3461d/PyExceptionInfo-0.1-py2-none-any.whl", "yanked": false}, {"comment_text": "", "digests": {"md5": "47245443d55d35f72c5cc5af2b609fac", "sha256": "f67f54303c217a2d28ade832ff9f6c8af75165a7b9e2574c9be5740ad62cb4ed"}, "downloads": -1, "filename": "PyExceptionInfo-0.1.zip", "has_sig": false, "md5_digest": "47245443d55d35f72c5cc5af2b609fac", "packagetype": "sdist", "python_version": "source", "requires_python": null, "size": 4403, "upload_time": "2016-07-04T18:50:08", "upload_time_iso_8601": "2016-07-04T18:50:08.829908Z", "url": "https://files.pythonhosted.org/packages/3f/aa/7b3db684076cbba4706578afdbc5c5522bc835fd120cd8c5f00f5a34bda5/PyExceptionInfo-0.1.zip", "yanked": false}], "0.2": [{"comment_text": "", "digests": {"md5": "a2466e7b53d0904692675b39bfb5b9a2", "sha256": "84966f02737a3435125bac68195ea1ffa003c359c9c8787f50e13057a292a419"}, "downloads": -1, "filename": "PyExceptionInfo-0.2-py2-none-any.whl", "has_sig": false, "md5_digest": "a2466e7b53d0904692675b39bfb5b9a2", "packagetype": "bdist_wheel", "python_version": "py2", "requires_python": null, "size": 2877, "upload_time": "2016-07-04T19:23:16", "upload_time_iso_8601": "2016-07-04T19:23:16.522048Z", "url": "https://files.pythonhosted.org/packages/fc/71/e10b5e163e764974e45b47e7767000891fd32375aa97fe9d22127b7dcf81/PyExceptionInfo-0.2-py2-none-any.whl", "yanked": false}, {"comment_text": "", "digests": {"md5": "fbf2ddc4027924cb38b21d868973a730", "sha256": "fa93bccb7c875e67449472c1e4649605ecdd30df3744138b2e75ab1cba18f6a9"}, "downloads": -1, "filename": "PyExceptionInfo-0.2.zip", "has_sig": false, "md5_digest": "fbf2ddc4027924cb38b21d868973a730", "packagetype": "sdist", "python_version": "source", "requires_python": null, "size": 4451, "upload_time": "2016-07-04T19:23:00", "upload_time_iso_8601": "2016-07-04T19:23:00.146426Z", "url": "https://files.pythonhosted.org/packages/a3/40/5d4e521cde9abeb1c5c2853391115e2066d73bfa7d2685d3bd4f79bc259e/PyExceptionInfo-0.2.zip", "yanked": false}]}, "urls": [{"comment_text": "", "digests": {"md5": "a2466e7b53d0904692675b39bfb5b9a2", "sha256": "84966f02737a3435125bac68195ea1ffa003c359c9c8787f50e13057a292a419"}, "downloads": -1, "filename": "PyExceptionInfo-0.2-py2-none-any.whl", "has_sig": false, "md5_digest": "a2466e7b53d0904692675b39bfb5b9a2", "packagetype": "bdist_wheel", "python_version": "py2", "requires_python": null, "size": 2877, "upload_time": "2016-07-04T19:23:16", "upload_time_iso_8601": "2016-07-04T19:23:16.522048Z", "url": "https://files.pythonhosted.org/packages/fc/71/e10b5e163e764974e45b47e7767000891fd32375aa97fe9d22127b7dcf81/PyExceptionInfo-0.2-py2-none-any.whl", "yanked": false}, {"comment_text": "", "digests": {"md5": "fbf2ddc4027924cb38b21d868973a730", "sha256": "fa93bccb7c875e67449472c1e4649605ecdd30df3744138b2e75ab1cba18f6a9"}, "downloads": -1, "filename": "PyExceptionInfo-0.2.zip", "has_sig": false, "md5_digest": "fbf2ddc4027924cb38b21d868973a730", "packagetype": "sdist", "python_version": "source", "requires_python": null, "size": 4451, "upload_time": "2016-07-04T19:23:00", "upload_time_iso_8601": "2016-07-04T19:23:00.146426Z", "url": "https://files.pythonhosted.org/packages/a3/40/5d4e521cde9abeb1c5c2853391115e2066d73bfa7d2685d3bd4f79bc259e/PyExceptionInfo-0.2.zip", "yanked": false}], "timestamp": "Fri May  8 03:06:08 2020"}